
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
sensor: !include_dir_merge_list sensors/
template: !include template.yaml
multiscrape: !include multiscrape.yaml
#scrape: !include scrape.yaml

shell_command:
  get_nba_first_round: 'python /config/www/nba-1st.py'
  get_nhl_first_round: 'python /config/www/nhl-1st.py'
  get_nba_first_round_grok: 'python /config/www/nba-1st-grok.py'
  get_nhl_first_round_grok: 'python /config/www/nhl-1st-grok.py'
  get_wnba_first_round_grok: 'python /config/www/wnba-1st-grok.py'
