
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
sensor: !include_dir_merge_list sensors/
template: !include template.yaml
multiscrape: !include multiscrape.yaml
#scrape: !include scrape.yaml
