###
## MLB Teams
##
- platform: teamtracker
  league_id: MLB
  team_id: LAA
  name: Los Angeles Angels
- platform: teamtracker
  league_id: MLB
  team_id: CHW
  name: Chicago White Sox
- platform: teamtracker
  league_id: MLB
  team_id: CLE
  name: Cleveland Guardians
- platform: teamtracker
  league_id: MLB
  team_id: KC
  name: Kansas City Royals
- platform: teamtracker
  league_id: MLB
  team_id: MIL
  name: Milwaukee Brewers
- platform: teamtracker
  league_id: MLB
  team_id: OAK
  name: Oakland Athletics
- platform: teamtracker
  league_id: MLB
  team_id: SEA
  name: Seattle Mariners
- platform: teamtracker
  league_id: MLB
  team_id: TEX
  name: Texas Rangers
- platform: teamtracker
  league_id: MLB
  team_id: CHC
  name: Chicago Cubs
- platform: teamtracker
  league_id: MLB
  team_id: CIN
  name: Cincinnati Reds
- platform: teamtracker
  league_id: MLB
  team_id: LAD
  name: Los Angeles Dodgers
- platform: teamtracker
  league_id: MLB
  team_id: SD
  name: San Diego Padres
- platform: teamtracker
  league_id: MLB
  team_id: SF
  name: San Francisco Giants
- platform: teamtracker
  league_id: MLB
  team_id: COL
  name: Colorado Rockies
- platform: teamtracker
  league_id: MLB
  team_id: ARI
  name: Arizona Diamondbacks
- platform: teamtracker
  league_id: MLB
  team_id: BAL
  name: Baltimore Orioles
- platform: teamtracker
  league_id: MLB
  team_id: BOS
  name: Boston Red Sox
- platform: teamtracker
  league_id: MLB
  team_id: DET
  name: Detroit Tigers
- platform: teamtracker
  league_id: MLB
  team_id: MIN
  name: Minnesota Twins
- platform: teamtracker
  league_id: MLB
  team_id: NYY
  name: New York Yankees
- platform: teamtracker
  league_id: MLB
  team_id: TOR
  name: Toronto Blue Jays
- platform: teamtracker
  league_id: MLB
  team_id: ATL
  name: Atlanta Braves
- platform: teamtracker
  league_id: MLB
  team_id: HOU
  name: Houston Astros
- platform: teamtracker
  league_id: MLB
  team_id: WSH
  name: Washington Nationals
- platform: teamtracker
  league_id: MLB
  team_id: NYM
  name: New York Mets
- platform: teamtracker
  league_id: MLB
  team_id: PHI
  name: Philadelphia Phillies
- platform: teamtracker
  league_id: MLB
  team_id: PIT
  name: Pittsburgh Pirates
- platform: teamtracker
  league_id: MLB
  team_id: STL
  name: St. Louis Cardinals
- platform: teamtracker
  league_id: MLB
  team_id: MIA
  name: Miami Marlins
- platform: teamtracker
  league_id: MLB
  team_id: TB
  name: Tampa Bay Rays

##
## MLB Standings
##
- platform: rest
  scan_interval: 36000
  name: MLB Standings
  unique_id: sensor.mlb_standings
  resource: https://site.web.api.espn.com/apis/v2/sports/baseball/mlb/standings?seasontype=2&type=0&level=3
  value_template: "{{ now() }}"
  json_attributes:
      - children
      
##
## Wildcards
##
- platform: rest
  scan_interval: 36000
  name: "MLB Wildcard"
  unique_id: mlb_wildcard
  icon: mdi:baseball
  resource: https://site.web.api.espn.com/apis/v2/sports/baseball/mlb/standings?region=us&lang=en&contentorigin=espn&type=3&level=2&sort=playoffseed%3Aasc%2Cpoints%3Adesc%2Cgamesplayed%3Aasc%2Crotwins%3Adesc&seasontype=2
  value_template: "{{ now() }}"  
  json_attributes:
      - children
      - overall      
##
## Playoff Standings
##
- platform: rest
  scan_interval: 36000
  name: "MLB PO Standings"
  unique_id: mlb_po_standings
  icon: mdi:baseball
  resource: https://site.web.api.espn.com/apis/v2/sports/baseball/mlb/standings?region=us&lang=en&contentorigin=espn&type=3&level=3&sort=playoffseed:asc,points:desc,gamesplayed:asc,rotwins:desc&seasontype=2
  value_template: "{{ now() }}"
  json_attributes:
      - children
      - overall
      
##
## Playoff Standings - Postseason
##
- platform: rest
  scan_interval: 36000
  name: "MLB Standings Postseason"
  unique_id: mlb_standings_postseason
  icon: mdi:baseball
  resource: https://site.api.espn.com/apis/site/v2/sports/baseball/mlb/scoreboard?limit=1000&dates=
  value_template: "{{ now() }}" 
  json_attributes:
      - leagues
  
##
## Schedule
##
- platform: rest
  # every 24 hours
  scan_interval: 86400
  name: "MLB Schedule"
  unique_id: mlb_schedule
  resource: https://site.api.espn.com/apis/site/v2/sports/baseball/mlb/scoreboard
  value_template: "{{ now() }}"
  json_attributes:
      - events
  
