##
## NHL Standings
##
- platform: rest
  scan_interval: 86400
  name: NHL Standings
  unique_id: sensor.nhl_standings
  resource: https://site.web.api.espn.com/apis/v2/sports/hockey/nhl/standings?seasontype=2&type=0&level=3
  value_template: "{{ now() }}"
  json_attributes:
      - children
##
## NHL Wildcard
##
- platform: rest
  scan_interval: 86400
  name: NHL Wildcard
  unique_id: sensor.nhl_wildcard
  resource: https://site.web.api.espn.com/apis/v2/sports/hockey/nhl/standings?region=us&lang=en&contentorigin=espn&type=3&level=2&sort=playoffseed%3Aasc%2Cpoints%3Adesc%2Cgamesplayed%3Aasc%2Crotwins%3Adesc&seasontype=2
  value_template: "{{ now() }}"
  json_attributes:
      - children
      - overall



###
### NHL Divisions
###


- platform: rest
  scan_interval: 604800
  name: NHL West Central
  unique_id: sensor.nhl_west_central
  resource: https://site.web.api.espn.com/apis/v2/sports/hockey/nhl/standings?seasontype=2&type=0&level=3
  value_template: "{{ now() }}"
  json_attributes_path: "$.[1]['children'][0]['standings']"
  json_attributes: 
   - entries   
  

- platform: rest
  scan_interval: 604800
  name: NHL West Pacific
  unique_id: sensor.nhl_west_pacific
  resource: https://site.web.api.espn.com/apis/v2/sports/hockey/nhl/standings?seasontype=2&type=0&level=3
  value_template: "{{ now() }}"
  json_attributes_path: "$.[1]['children'][1]['standings']"
  json_attributes: 
   - entries   
  

- platform: rest
  scan_interval: 604800
  name: NHL East Atlantic
  unique_id: sensor.nhl_east_atlantic
  resource: https://site.web.api.espn.com/apis/v2/sports/hockey/nhl/standings?seasontype=2&type=0&level=3
  value_template: "{{ now() }}"
  json_attributes_path: "$.[0]['children'][0]['standings']"
  json_attributes: 
   - entries   
  

- platform: rest
  scan_interval: 604800
  name: NHL East Metropolitan
  unique_id: sensor.nhl_east_metropolitan
  resource: https://site.web.api.espn.com/apis/v2/sports/hockey/nhl/standings?seasontype=2&type=0&level=3
  value_template: "{{ now() }}"
  json_attributes_path: "$.[0]['children'][1]['standings']"
  json_attributes: 
   - entries   

- platform: rest
  scan_interval: 86400
  name: starstest2_schedule_regular_season
  unique_id: sensor.starstest2_schedule_regular_season
  resource: https://site.api.espn.com/apis/personalized/v2/scoreboard/header?sport=hockey&league=nhl&team=dal?seasontype=2&type=0&level=3
  value_template: "{{ now() }}"
  json_attributes_path: "$['sports'][0]['leagues'][0]"
  json_attributes: 
   - events

#- platform: rest
  #scan_interval: 86400
  #name: Dallas_stars_test_schedule_regular_season
  #unique_id: sensor.dallas_stars_test_schedule_regular_season
  #resource: http://site.api.espn.com/apis/site/v2/sports/hockey/nhl/teams/dal/schedule?seasontype=2&type=0&level=3
  #value_template: "{{ now() }}"
  #json_attributes: 
   #- team
   #- events   
    
#- platform: rest
  #scan_interval: 604800
  #name: Dallas Stars Standings
  #unique_id: sensor.nhl_dallas_stars_standings
  #value_template: "{{ now() }}"
  #json_attributes_path: "$.[1]['children'][0]['standings']"
  #json_attributes: 
   #- entries   
  #attributes:
    #entries: "{{ state_attr('sensor.nhl_standings','children')[1]['children'][0]['standings']['entries'][1] }}"



#
##  NHL Teams
##
- platform: teamtracker
  league_id: NHL
  team_id: DET
  name: Detroit Red Wings
- platform: teamtracker
  league_id: NHL
  team_id: NSH
  name: Nashville Predators
- platform: teamtracker
  league_id: NHL
  team_id: FLA
  name: Florida Panthers
- platform: teamtracker
  league_id: NHL
  team_id: STL
  name: St Louis Blues
- platform: teamtracker
  league_id: NHL
  team_id: COL
  name: Colorado Avalanche
- platform: teamtracker
  league_id: NHL
  team_id: BOS
  name: Boston Bruins
- platform: teamtracker
  league_id: NHL
  team_id: NYI
  name: New York Islanders
- platform: teamtracker
  league_id: NHL
  team_id: PIT
  name: Pittsburg Penguins
- platform: teamtracker
  league_id: NHL
  team_id: NJ
  name: New Jersey Devils
  
- platform: teamtracker
  league_id: NHL
  team_id: DAL
  name: Dallas Stars
  
- platform: rest
  scan_interval: 86400
  name: nhl_schedule_dallas_stars
  unique_id: sensor.nhl_schedule_dallas_stars
  resource: https://site.api.espn.com/apis/site/v2/sports/hockey/nhl/teams/dal/schedule?seasontype=2&type=0&level=3
  value_template: "{{ now() }}"
  json_attributes:
      - team
      - events 
      
- platform: teamtracker
  league_id: NHL
  team_id: CBJ
  name: Columbus Blue Jackets
- platform: teamtracker
  league_id: NHL
  team_id: TOR
  name: Toronto Maple Leafs
- platform: teamtracker
  league_id: NHL
  team_id: MTL
  name: Montreal Canadians
- platform: teamtracker
  league_id: NHL
  team_id: CAR
  name: Carolina Hurricanes
- platform: teamtracker
  league_id: NHL
  team_id: WSH
  name: Washington Senators
- platform: teamtracker
  league_id: NHL
  team_id: CGY
  name: Calgary Flames
- platform: teamtracker
  league_id: NHL
  team_id: NYR
  name: New York Rangers
- platform: teamtracker
  league_id: NHL
  team_id: VAN
  name: Vancouver Canucks
- platform: teamtracker
  league_id: NHL
  team_id: PHI
  name: Philadelphia Fylers
- platform: teamtracker
  league_id: NHL
  team_id: LA
  name: Los Angeles Kings
- platform: teamtracker
  league_id: NHL
  team_id: ARI
  name: Arizona Coyotes
- platform: teamtracker
  league_id: NHL
  team_id: SJ
  name: San Jose Sharks
- platform: teamtracker
  league_id: NHL
  team_id: BUF
  name: Buffalo Sabres
- platform: teamtracker
  league_id: NHL
  team_id: SEA
  name: Seattle Kraken
- platform: teamtracker
  league_id: NHL
  team_id: VGK
  name: Los Vegas Golden Knights
- platform: teamtracker
  league_id: NHL
  team_id: TB
  name: Tampa Bay Lightning
- platform: teamtracker
  league_id: NHL
  team_id: OTT
  name: Ottawa Senators
- platform: teamtracker
  league_id: NHL
  team_id: WPG
  name: Winnipeg Jets
- platform: teamtracker
  league_id: NHL
  team_id: EDM
  name: Edmonton Oilers
- platform: teamtracker
  league_id: NHL
  team_id: MIN
  name: Minnesota Wild
- platform: teamtracker
  league_id: NHL
  team_id: ANA
  name: Anaheim Ducks
- platform: teamtracker
  league_id: NHL
  team_id: CHI
  name: Chicago Blackhawks
  
