- platform: rest
  name: Fox News Breaking
  scan_interval: 360000
  unique_id: sensor.fox_new_breaking
  resource_template: https://moxie.foxnews.com/google-publisher/latest.xml
  value_template: "{{ now() }}"
  json_attributes_path: "$.rss"
  json_attributes:
    - channel
- platform: rest
  name: Fox News Sports
  scan_interval: 3600
  unique_id: sensor.fox_new_sports
  resource_template: https://moxie.foxnews.com/google-publisher/sports.xml
  value_template: "{{ now() }}"
  json_attributes_path: "$.rss"
  json_attributes:
    - channel
- platform: rest
  name: Fox News Politics
  scan_interval: 3600
  unique_id: sensor.fox_new_politics
  resource_template: https://moxie.foxnews.com/google-publisher/politics.xml
  value_template: "{{ now() }}"
  json_attributes_path: "$.rss"
  json_attributes:
    - channel
- platform: rest
  name: ESPN Top Headlines
  scan_interval: 3600
  unique_id: sensor.espn_top_headlines
  resource_template: https://www.espn.com/espn/rss/news
  value_template: "{{ now() }}"
  json_attributes_path: "$.rss"
  json_attributes:
    - channel
- platform: rest
  name: CBS Sports Top MLB Headlines
  scan_interval: 3600
  unique_id: sensor.cbs_sports_top_mlb_headlines
  resource_template: https://www.cbssports.com/rss/headlines/mlb/
  value_template: "{{ now() }}"
  json_attributes_path: "$.rss"
  json_attributes:
    - channel
- platform: rest
  name: Yahoo Sports Top MLB Headlines
  scan_interval: 3600
  unique_id: sensor.yahoo_sports_top_mlb_headlines
  resource_template: https://sports.yahoo.com/mlb/rss/
  value_template: "{{ now() }}"
  json_attributes_path: "$.rss"
  json_attributes:
    - channel
- platform: rest
  name: CBS 8 San Diego Local News
  scan_interval: 3600
  unique_id: sensor.cbs8_headlines
  resource_template: https://feeds.feedblitz.com/cbs8/local
  value_template: "{{ now() }}"
  json_attributes_path: "$.rss"
  json_attributes:
    - channel
- platform: rest
  name: Blocks and Files
  scan_interval: 3600
  unique_id: sensor.blocks_and_files
  resource_template: https://blocksandfiles.com/feed/
  value_template: "{{ now() }}"
  json_attributes_path: "$.rss"
  json_attributes:
    - channel
- platform: rest
  name: Movies Currently in Theaters
  scan_interval: 3600
  unique_id: sensor.movies_currently_in_theaters
  resource_template: https://www.filmjabber.com/rss/rss-current.php
  value_template: "{{ now() }}"
  json_attributes_path: "$.rss"
  json_attributes:
    - channel
- platform: rest
  name: Movie news
  scan_interval: 3600
  unique_id: sensor.movie_new
  resource_template: https://www.moviefone.com/feeds/news.rss 
  value_template: "{{ now() }}"
  json_attributes_path: "$.rss"
  json_attributes:
    - channel
- platform: rest
  name: Movie Trailers
  scan_interval: 3600
  unique_id: sensor.movie_trailers
  resource_template: https://www.moviefone.com/feeds/movie-trailers.rss
  value_template: "{{ now() }}"
  json_attributes_path: "$.rss"
  json_attributes:
    - channel
- platform: file
  name: SDSC 2024-2025 League Standings
  unique_id: sensor.sdsc_2024_league_standings
  file_path: /config/ecrl.json
  value_template: "{{ value_json.headers }}"  # Just a placeholder
  json_attributes:
      - headers
      - rows
